# Gateway local: cumple el mismo rol que el ALB de AWS (routing por path).
# / -> front (estatico) | /api-ventas/* -> back-ventas | /api-despachos/* -> back-despachos
server {
    listen 80;
    server_name _;

    location /api-ventas/ {
        proxy_pass http://back-ventas:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api-despachos/ {
        proxy_pass http://back-despachos:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://front:80;
        proxy_set_header Host $host;
    }
}
