version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: innovatech-frontend:latest
    container_name: innovatech_frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_HOST=${BACKEND_HOST}   # ← se inyecta desde .env
    restart: unless-stopped