apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  # ClusterIP (interno). Los backends lo alcanzan por el nombre DNS "mysql".
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
